parameters:
    ibnab_pmanager.tcpdf.class: Ibnab\Bundle\PmanagerBundle\Controller\TCPDFController
    ibnab_pmanager.pdftemplate.entity.class:   Ibnab\Bundle\PmanagerBundle\Entity\PDFTemplate
    ibnab_pmanager.producttemplate.entity.class: Ibnab\Bundle\PmanagerBundle\Entity\ProductTemplate
    ibnab_pmanager.publication.entity.class: Ibnab\Bundle\PmanagerBundle\Entity\Publication
    ibnab_pmanager.logs.entity.class:   Ibnab\Bundle\PmanagerBundle\Entity\Logs
    ibnab_pmanager.pdftemplate.manager.class:       Ibnab\Bundle\PmanagerBundle\Entity\Manager\PDFTemplateActivityManager
    ibnab_pmanager.twig.pdftemplate_security_policy.class: Twig_Sandbox_SecurityPolicy
    ibnab_pmanager.twig.extension.pdftemplate.class:    Ibnab\Bundle\PmanagerBundle\Twig\PDFTemplateExtension
    
    # Providers    
    ibnab_pmanager.pdftemplate.variable_provider.class: Ibnab\Bundle\PmanagerBundle\Provider\VariablesProvider
    ibnab_pmanager.pdftemplate.variable_provider.entity.class: Ibnab\Bundle\PmanagerBundle\Provider\EntityVariablesProvider
    ibnab_pmanager.pdftemplate.variable_provider.system.class: Ibnab\Bundle\PmanagerBundle\Provider\SystemVariablesProvider
    ibnab_pmanager.pdftemplate.variable_provider.user.class: Ibnab\Bundle\PmanagerBundle\Provider\LoggedUserVariablesProvider
    
    # Cache keys
    ibnab_pmanager.cache.available_in_template_key: 'ibnab_pmanager.available_in_template_fields'

    # pdf template renderer, twig instance
    ibnab_pmanager.pdftemplate_renderer.class: Ibnab\Bundle\PmanagerBundle\Provider\PDFTemplateRenderer
    #ibnab_pmanager.producttemplate_renderer.class: Ibnab\Bundle\PmanagerBundle\Provider\ProductTemplateRenderer
    #ibnab_pmanager.publication_renderer.class: Ibnab\Bundle\PmanagerBundle\Provider\PublicationRenderer
    ibnab_pmanager.twig._security_policy.class: Twig_Sandbox_SecurityPolicy

    #ibnab_pmanager.helper.datagrid.pdftemplate.class:           Ibnab\Bundle\PmanagerBundle\Datagrid\PDFTemplateGridHelper1
    #ibnab_pmanager.datagrid_query_factory.class:           Ibnab\Bundle\PmanagerBundle\Datagrid\PDFTemplateQueryFactory
    ibnab_pmanager.pdftemplate.datagrid_view_list.class: Ibnab\Bundle\PmanagerBundle\Datagrid\PDFTemplateViewList
    ibnab_pmanager.pdftemplate.datagrid_helper.class:    Ibnab\Bundle\PmanagerBundle\Datagrid\PDFTemplateGridHelper

    ibnab_pmanager.pdftemplate.owner.provider.storage.class: Ibnab\Bundle\PmanagerBundle\Entity\Provider\PDFTempalteOwnerProviderStorage
    ibnab_pmanager.pdftemplate.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    ibnab_pmanager.activity_list.provider.class:       Ibnab\Bundle\PmanagerBundle\Provider\PmanagerActivityListProvider
    ibnab_pmanager.placeholder.filter.class:            Ibnab\Bundle\PmanagerBundle\Placeholder\PlaceholderFilter  
    # Config provider
    ibnab_pmanager.provider.configuration.class:         Ibnab\Bundle\PmanagerBundle\Provider\ConfigurationProvider  
    oro_email.provider.email_recipients.helper.class: Ibnab\Bundle\PmanagerBundle\Provider\EmailRecipientsHelper

services: 
#    ibnab_pmanager.example:
#        class: %ibnab_pmanager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
         # Form Types
    ibnab_pmanager.provider.configuration:
        class: %ibnab_pmanager.provider.configuration.class%
        arguments:
            - '@oro_config.global'
            - '@oro_entity.doctrine_helper'
            - '%oro_attachment.attachments_dir%'
    # Email template API
    ibnab_pmanager.pdftemplate.api:
        class: %ibnab_pmanager.pdftemplate.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ibnab_pmanager.pdftemplate.entity.class%
            - '@doctrine.orm.entity_manager'
    ibnab_pmanager.producttemplate.api:
        class: %ibnab_pmanager.pdftemplate.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ibnab_pmanager.producttemplate.entity.class%
            - '@doctrine.orm.entity_manager'
    ibnab_pmanager.logs.api:
        class: %ibnab_pmanager.pdftemplate.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ibnab_pmanager.logs.entity.class%
            - '@doctrine.orm.entity_manager'
    ibnab_pmanager.pdftemplate.datagrid_helper:
        class: %ibnab_pmanager.pdftemplate.datagrid_helper.class%
        arguments:
            - '@oro_entity.entity_provider'
            - '@translator'
    ibnab_pmanager.pdftemplate.datagrid_view_list:
        class: %ibnab_pmanager.pdftemplate.datagrid_view_list.class%
        arguments:
            - '@translator'
    ibnab_pmanager.tcpdf:
        class: %ibnab_pmanager.tcpdf.class%
        file: %ibnab_pmanager.file%
        arguments:
            - %ibnab_pmanager.class%
        tags:
            - { name: pmanager.tcpdf, alias: pmanager_tcpdf }

    ibnab_pmanager.cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['ibnab_pmanager.cache']]
    # email template twig instance
    # Available variables services
    ibnab_pmanager.listener.config_listener:
        class: Ibnab\Bundle\PmanagerBundle\EventListener\EntityConfigListener
        arguments:
            - '@ibnab_pmanager.cache'
            - %ibnab_pmanager.cache.available_in_template_key%
        tags:
            - { name: kernel.event_listener, event: oro.entity_config.pre_flush, method: preFlush }
    ibnab_pmanager.twig.string_loader:
        class: Twig_Loader_String
    ibnab_pmanager.pdftemplate_renderer:
        class: %ibnab_pmanager.pdftemplate_renderer.class%
        arguments:
            - '@ibnab_pmanager.twig.string_loader'
            -  # twig environment options
              strict_variables: true
            - '@ibnab_pmanager.pdftemplate.variable_provider'
            - '@ibnab_pmanager.cache'
            - %ibnab_pmanager.cache.available_in_template_key%
            - '@ibnab_pmanager.twig.pdftemplate_sandbox'
            - '@translator'
            - '@oro_email.emailtemplate.variable_processor'
            - '@oro_locale.settings'
            - '@doctrine'
            - '@oro_locale.helper.localization'
            - '@service_container'
        lazy: true
    ibnab_pmanager.twig.pdftemplate_sandbox:
        class: Twig_Extension_Sandbox
        arguments:
            - '@ibnab_pmanager.twig.security_policy'
            - true # use sandbox globally in instance
    ibnab_pmanager.pdftemplate.variable_provider:
        class: %ibnab_pmanager.pdftemplate.variable_provider.class%

    ibnab_pmanager.pdftemplate.variable_provider.entity:
        class: %ibnab_pmanager.pdftemplate.variable_provider.entity.class%
        arguments:
            - '@translator'
            - '@oro_entity_config.config_manager'
            - '@doctrine'
            - '@oro_ui.formatter'
        lazy: true
        public: false
        tags:
            - { name: ibnab_pmanager.pdftemplate.variable_provider, scope: entity }
    ibnab_pmanager.provider.payment_method_object_variables:
        class: 'Oro\Bundle\PaymentBundle\Provider\PaymentMethodObjectVariablesProvider'
        lazy: true
        public: false
        tags:
            - { name: ibnab_pmanager.pdftemplate.variable_provider, scope: entity }
    ibnab_pmanager.twig.security_policy:
        class: %oro_email.twig.email_security_policy.class%
        arguments:
            # tags
            - [ 'app', 'for', 'if', 'spaceless' ]
            # filters
            - [ 'default','label','getlabel', 'date', 'escape', 'format', 'length', 'lower', 'nl2br', 'number_format', 'title', 'trim', 'upper' ,'oro_format_currency', 'oro_html_sanitize', 'oro_format_name' ]
            # methods
            - ['label','getlabel']
            # properties
            - []
            # functions
            - [ 'date' ,'label','getlabel']
    ibnab_pmanager.pdftemplate.variable_provider.system:
        class: %ibnab_pmanager.pdftemplate.variable_provider.system.class%
        lazy: true
        arguments:
            - '@translator'
            - '@oro_config.user'
            - '@oro_locale.formatter.date_time'
        lazy: true
        public: false
        tags:
            - { name: ibnab_pmanager.pdftemplate.variable_provider, scope: system }

    ibnab_pmanager.pdftemplate.variable_provider.user:
        class: %ibnab_pmanager.pdftemplate.variable_provider.user.class%
        lazy: true
        arguments:
            - '@translator'
            - '@oro_security.token_accessor'
            - '@oro_entity.entity_name_resolver'
            - '@oro_config.user'
        lazy: true
        public: false
        tags:
            - { name: ibnab_pmanager.pdftemplate.variable_provider, scope: system }
    ibnab_pmanager.validator.pdf_template_syntax:
        class: Ibnab\Bundle\PmanagerBundle\Validator\PDFTemplateSyntaxValidator
        arguments:
            - '@ibnab_pmanager.pdftemplate_renderer'
            - '@oro_locale.settings'
            - '@oro_config.user'
            - '@oro_entity_config.provider.entity'
            - '@translator'
        tags:
            - { name: validator.constraint_validator, alias: ibnab_pmanager.pdftemplate_syntax_validator }
            
    ibnab_pmanager.pdftemplate.owner.provider.storage:
        public: false
        class: %ibnab_pmanager.pdftemplate.owner.provider.storage.class%
    ibnab_pmanager.pdftemplate.form.autocomplete.getpdf.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %ibnab_pmanager.pdftemplate.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: PDFtemplates, acl_resource: pmanager_defaut_view }
    ibnab_pmanager.widget_provider.actions:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - ibnab_pmanager_add_button
            - ibnab_pmanager_add_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: 100 }
            - { name: oro_ui.update_action_provider, group: activity, priority: 100 }
    ibnab_pmanager.placeholder.filter:
        class: %ibnab_pmanager.placeholder.filter.class%
        arguments:
            - '@ibnab_pmanager.provider.configuration'
            - '@oro_entity.doctrine_helper' 
    ibnab_pmanager.form.autocomplete.type.update.pdftemplate_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%ibnab_pmanager.pdftemplate.entity.class%'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: pmanager_template_autocomplete, acl_resource: pmanager_template_index }

    ibnab_pmanager.datagrid.mass_action.handler.delete:
        class: Ibnab\Bundle\PmanagerBundle\Datagrid\MassAction\DeleteMassActionHandler
        parent: oro_datagrid.extension.mass_action.handler.delete
        calls:
            - [setDeleteManager, ['@ibnab_pmanager.logs.delete_manager']]
    ibnab_pmanager.logs.delete_manager:
        class: 'Ibnab\Bundle\PmanagerBundle\Manager\Logs\DeleteManager'
        public: false
        arguments:
            - '@doctrine'

