placeholders:
    items:
        ibnab_pmanager_add_button:
            template: IbnabPmanagerBundle:Pmanager:activityButton.html.twig
            applicable: "@ibnab_pmanager.placeholder.filter->isApplicable($entity$)"
            acl: pmanager_defaut_createview
        ibnab_pmanager_add_link:
            template: IbnabPmanagerBundle:Pmanager:activityLink.html.twig
            applicable: "@ibnab_pmanager.placeholder.filter->isApplicable($entity$)"
            acl: pmanager_defaut_createview
