pmanager_template_api:
    resource: Ibnab\Bundle\PmanagerBundle\Controller\Api\Rest\PDFTemplateController
    type: rest
pmanager_logs_api:
    resource: Ibnab\Bundle\PmanagerBundle\Controller\Api\Rest\LogsController
    type: rest
pmanager_producttemplate_api:
    resource: Ibnab\Bundle\PmanagerBundle\Controller\Api\Rest\ProductTemplateController
    type: rest
pmanager_publication_api:
    resource: Ibnab\Bundle\PmanagerBundle\Controller\Api\Rest\PublicationController
    type: rest